clear all;clc;
%system('module load fsl/6.0.2');
basedir = '/bcbl/home/home_g-m/jbarry/diffusion/TOT_PREV/';
container='anatrois';
version='4.2.7-7.1.1';
analysis='analysis-TOT_PREV';

projPath = fullfile(basedir,'nifti','derivatives',...
    strcat(container,'_',version),analysis);

subSesList    = fullfile(projPath,'subSesList.txt');
opts          = detectImportOptions(subSesList);
opts = setvartype(opts,{'sub','ses','RUN','anat','dwi','func'},...
                       {'categorical',...
                       'categorical',...
                       'logical',...
                       'logical',...
                       'logical',...
                       'logical'});
ssl           = readtable(subSesList,opts); 
subs = unique(ssl.sub);
ssl = ssl(ssl.dwi==true,:);
rows = unique(ssl(:,{'sub','ses'}));

% % Define ROIs list to merge and their merged name

ROIformat = '.nii.gz';

ROIlist = {{'L_Area_8BM','L_Area_9_Middle'},...
           {'R_Area_8BM','R_Area_9_Middle'},...
           {'L_ParaHippocampal_Area_1','L_ParaHippocampal_Area_2','L_ParaHippocampal_Area_3'},...
           {'R_ParaHippocampal_Area_1','R_ParaHippocampal_Area_2','R_ParaHippocampal_Area_3'},...
           {'L_Area_23c','L_Area_23d'},...
           {'R_Area_23c','R_Area_23d'},...
           {'L_Area_PFm_Complex','L_Area_PGi','L_Area_PGs'},...
           {'R_Area_PFm_Complex','R_Area_PGi','R_Area_PGs'},...
           {'L_Area_s32','L_Area_25','L_Area_10r','L_Area_10v'},...
           {'R_Area_s32','R_Area_25','R_Area_10r','R_Area_10v'}};

for rl = 1:length(ROIlist)
    ROIlist{rl} = append(ROIlist{rl},ROIformat);
end

mergedROInames = {'Left_mPFC',...
                  'Right_mPFC',...
                  'Left-ParaHippocampal',...
                  'Right-ParaHippocampal',...
                  'Left_PosteriorCingulate',...
                  'Right_PosteriorCingulate',...
                  'Left_AngGy',...
                  'Right_AngGy',...
                  'Left_vmPFC',...
                  'Right_vmPFC'};
              
if (length(ROIlist) ~= length(mergedROInames))
    error("Merged ROI names must contain ROI to merge");
end

%% Iterate through each subject on the list
for nr = 1:height(rows)
    sub = char(rows.sub(nr));
    ses = char(rows.ses(nr));
    
    subdir = fullfile(projPath,...
                      strcat('sub-',sub),...
                      strcat('ses-',ses));
    
    unzip(fullfile(subdir,'output','fs.zip'),fullfile(subdir,'output'));              
    
    ROIdir = fullfile(subdir,'output','fs','ROIs');
    niiFiles = dir(fullfile(ROIdir, '*.nii*'));
    
    ROIs = cell(1,length(niiFiles));
    for K = 1 : length(niiFiles)
      ROIs{K} = niiFiles(K).name;
    end
    
    % create tmpdirectory where to process ROI
    ROItmp = fullfile(subdir,'output','tmp','ROIs');
    if ~exist(ROItmp, 'dir')
        mkdir(ROItmp)
    end
    
    for rl = 1:numel(ROIlist)
        ROIs2merge = ROIlist{rl};
        if ~isequal(sum(ismember(ROIs2merge,ROIs)), numel(ROIs2merge))
            error('Missing some of these ROIs:\n %s\n',ROIs2merge{:})
        end
        % % % % %
        if numel(ROIs2merge) < 2
            error('You must have at least 2 ROIs to merge')
        elseif numel(ROIs2merge) == 2
            cmdFslmaths = append('fslmaths ',...
                                 fullfile(ROIdir,ROIs2merge{1}),...
                                 ' -add ',...
                                 fullfile(ROIdir,ROIs2merge{2}),' ',...
                                 fullfile(ROItmp,mergedROInames{rl}));
        elseif numel(ROIs2merge) == 3
            cmdFslmaths = append('fslmaths ',...
                                 fullfile(ROIdir,ROIs2merge{1}),...
                                 ' -add ',...
                                 fullfile(ROIdir,ROIs2merge{2}),...
                                 ' -add ',...
                                 fullfile(ROIdir,ROIs2merge{3}),' ',...
                                 fullfile(ROItmp,mergedROInames{rl}));
        elseif numel(ROIs2merge) == 4
            cmdFslmaths = append('fslmaths ',...
                                 fullfile(ROIdir,ROIs2merge{1}),...
                                 ' -add ',...
                                 fullfile(ROIdir,ROIs2merge{2}),...
                                 ' -add ',...
                                 fullfile(ROIdir,ROIs2merge{3}),...
                                 ' -add ',...
                                 fullfile(ROIdir,ROIs2merge{4}),' ',...
                                 fullfile(ROItmp,mergedROInames{rl}));
        end
        system(cmdFslmaths);
    end
    copyfile(fullfile(ROItmp,'*.nii.gz'),ROIdir);
    zip(fullfile(subdir,'output','fs.zip'),fullfile(subdir,'output','fs'));
    system(append('rm -rf ',fullfile(subdir,'output','fs')));
end